repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: no-commit-to-branch
    -   id: check-merge-conflict
- repo: git://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.6
  hooks:
  - id: forbid-tabs
    exclude_types: [python, javascript, dtd, markdown, makefile, xml]
    exclude: binary|\.bin$
- repo: git://github.com/kintoandar/pre-commit.git
  rev: v2.1.0
  hooks:
  - id: terraform_fmt
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v2.2.1
  stages:
  - commit
  - push
  hooks:
  -   id: detect-aws-credentials
  -   id: detect-private-key
- repo: https://github.com/detailyang/pre-commit-shell
  rev: 1.0.4
  hooks:
  - id: shell-lint
- repo: git://github.com/igorshubovych/markdownlint-cli
  rev: v0.15.0
  hooks:
  - id: markdownlint
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v6.0.0-alpha.0
  hooks:
  -  id: eslint
  additional_dependencies:
  - eslint@5.16.0
  - eslint-config-airbnb@17.1.0
  - eslint-config-prettier@4.2.0
  - eslint-plugin-import@2.17.2
  - eslint-plugin-prettier@3.0.1
  - prettier@1.17.0
