---
# yamllint disable rule:line-length
name: Pull Request
on:
  pull_request:
  workflow_dispatch:

env:
  terraform: 1.3.0
  tf_target_dir: example/examplea

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          token: ${{ github.token }}
          fetch-depth: '0'
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.terraform }}
          tf_actions_subcommand: init
          tf_actions_working_dir: ${{ env.tf_target_dir }}
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.terraform }}
          tf_actions_subcommand: validate
          tf_actions_working_dir: example/examplea
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          token: ${{ github.token }}
          fetch-depth: '0'
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.8
      - uses: pre-commit/action@v3.0.0
